server {
    listen 80;
    server_name __DOMAIN__;
    server_tokens off;

    # Certbot webroot validation
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    location / {
        return 200 'ArkManiaGest - setup in progress...\n';
        add_header Content-Type text/plain;
    }
}
