"""
schemas/instance_action.py — Pydantic schemas for the instance action log.

Action log entries are generated by the ``ARKM_server_instances`` routes
every time a lifecycle operation is triggered (bootstrap, create, start,
stop, restart, update, backup, delete, rcon, pok_sync).  They remain in
the panel DB even after the related instance is deleted.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel


class ActionKind(str, Enum):
    """Known action kinds emitted into :class:`InstanceAction`."""

    BOOTSTRAP      = "bootstrap"       # install docker/pok on a machine
    CREATE         = "create"          # instantiate a new container
    START          = "start"
    STOP           = "stop"
    RESTART        = "restart"
    UPDATE         = "update"          # POK-manager self-update / ASA update
    BACKUP         = "backup"
    DELETE         = "delete"
    RCON           = "rcon"            # rcon command execution
    POK_SYNC       = "pok_sync"        # sync POK-manager script from reference
    PREREQS_CHECK  = "prereqs_check"   # docker/WSL availability check


class ActionStatus(str, Enum):
    """Lifecycle state of an action log entry."""

    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED  = "failed"


class InstanceActionRead(BaseModel):
    """A single audit row, safe to expose on the event log page."""

    id: int
    instance_id: Optional[int] = None
    machine_id: Optional[int] = None
    instance_name: Optional[str] = None

    action: ActionKind
    status: ActionStatus = ActionStatus.PENDING

    stdout: Optional[str] = None
    stderr: Optional[str] = None
    exit_code: Optional[int] = None
    meta: Optional[str] = None

    user_id: Optional[int] = None
    username: Optional[str] = None

    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    duration_ms: Optional[int] = None

    class Config:
        from_attributes = True
